# Generated by Django 5.0 on 2023-12-14 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('descriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('image', models.ImageField(upload_to='generated_images/%Y/%m/', verbose_name='image')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='descriptions.description', verbose_name='description')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
